name: Build and Publish to GitHub Packages

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'osama'  # Only run on your main repo

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # 3️⃣ Build the JAR
      - name: Build JAR
        run: mvn clean package -DskipTests

      # 4️⃣ Upload the build artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-package-demo
          path: target/*.jar

      # 5️⃣ Deploy to GitHub Packages
      - name: Publish to GitHub Packages
        run: mvn deploy -s .github/settings.xml -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
