name: Build and Publish Maven Package

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build JAR
        run: mvn clean package -DskipTests -U

      - name: Deploy to GitHub Packages
        run: mvn deploy -s .github/settings.xml -DskipTests -U
        env:
          GITHUB_ACTOR: ${{ secrets.ACTOR }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

